name: step
favicon: null
layout_spectrum: 0.3482586797326803
typography_spectrum: 0.6579210262279958
title: 'stephan mantler | photographer | mountain guide | hacker'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#030406'
    - '#1b3b50'
    - '#8a8f93'
    - '#c1bcc0'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
